# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Python CI

on:
  push:
    branches: [ main ] # Cambia "main" si tu rama principal tiene otro nombre.
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.8
      - name: Run tests
        run: |
            python -m unittest tests/test_suma.py
